version: '3.8'

services:
  backend:
    build: ./harbory-backend
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      
  frontend:
    build: 
      context: ./harbory-frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_APP_ENV=${VITE_APP_ENV}
        - VITE_APP_TITLE=${VITE_APP_TITLE}
        - VITE_DEBUG_MODE=${VITE_DEBUG_MODE}
        - VITE_API_TIMEOUT=${VITE_API_TIMEOUT}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
